{{- if .Values.externalSecret.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  labels:
    app: {{ .Release.Name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "externalSecret.roleArn is required when externalSecret is enabled" .Values.externalSecret.roleArn }}
{{- end }}
