{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Release.Name }}-secret-store
    kind: SecretStore
  target:
    name: ghcr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"auth":"{{ `{{ .token | b64enc }}` }}"}}}
  data:
    - secretKey: token
      remoteRef:
        key: /workshops/ghcr-token
{{- end }}
